# Site settings
title: Claire's Bracelets
email: claire@clairechevallier.com
description: > # this means to ignore newlines until "baseurl:"
  Hi. I'm Claire.<br><br>

  This is my wonderful fantastic bracelet website. Here you can find
  pictures and prices of my bracelets.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
